export default {
    claimBot: 'XEN Claim Bot',
    mobileVisitNotice: '请使用桌面浏览器访问此页',
    header: {
        xenft: 'XENFT',
        monitor: 'XEN监控',
        dashboard: '仪表盘',
        portfolio: '我的资产',
        miner: 'Miner',
        claimbot: 'ClaimBot'
    },
    footer: {
        slogan: '建设加密世界新未来',
        intro: 'CryptoCell Labs是一个专注于区块链行业研究、知识传播、数据分析的行业平台，力图帮助业内人士洞察行业走势、把握市场先机。',
        copyRights: '© 2022 CryptoCell Labs. All Rights Reserved.'
    },
    datetime: {
        days: '天',
        hours: '小时',
        minutes: '分钟',
        seconds: '秒'
    },
    importFileForm: {
        title: '导入文件',
        desc: '导入包含钱包地址和私钥的表格文件 (xls, xlsx, csv)',
        placeholder: '选择文件',
        notFound: '无表格文件',
        notSupported: '文件类型不支持',
        template: '示例文件',
        notAvailable: '没有可用的地址和私钥'
    },
    toClaim: '去提取XEN',
    toClaimDesc: '跳转至提取XEN页面前，将自动选择当前可提取的地址并加密保存至浏览器本地存储',
    addresses: '地址列表',
    clearAddresses: '清空地址',
    totalImported: '共导入',
    currentClaimable: '当前可提取',
    walletAddress: '钱包地址',
    status: '状态',
    noMintInfo: '无铸造信息',
    maturity: '到期时间',
    term: '锁定天数',
    paramsConfig: '参数配置',
    walletAddressToReceiveXEN: '收取XEN和余额的钱包地址',
    maxGwei: '最大Gwei',
    start: '开始',
    continue: '继续',
    pause: '暂停',
    ended: '已结束',
    startNewTask: '开始新任务',
    configForm: {
        pleaseInput: '请输入',
        walletAddressFormatError: '钱包地址格式不正确'
    },
    claimTips: {
        title: '提示',
        p1: '本程序是模拟人工操作的，需要确保电脑处于非待机状态并且网络环境稳定，开始提取任务后不要关闭此页面，也不要打开多个浏览器标签页进行同一操作。',
        p2: '本程序将按表格顺序执行提取XEN过程，每提取完一个钱包地址的XEN，将把余额转至下一个钱包，进行下一个钱包的提取任务，直至最后一个钱包，最后一个钱包的余额将转至收取XEN的钱包地址。',
        p3: '开始任务前，请确保第一个钱包地址的余额可满足整个提取和转账过程的花费，为避免过程中提前中止，建议多转一些，剩余部分会转回收取XEN的钱包地址。',
        p4: '过程中可调整最大Gwei，收取XEN的钱包地址不可调整。',
        p5: '本程序代码已开源，可点击右上角Github图标查看详情，使用过程中的网络通讯仅包含必要的与以太坊节点之间的通讯，产生的内容将保存在浏览器本地存储中。'
    },
    logs: '日志',
    logsType: {
        noContent: '暂无内容'
    },
    totalAddresses: '地址总数',
    claimStatus: '提取状态',
    transferStatus: '转账状态',
    balance: '余额',
    actions: '操作',
    taskStarted: '任务开始。',
    taskEnded: '任务结束。',
    taskPaused: '任务暂停。',
    taskContinue: '任务继续。',
    executingAddressItem: '正在执行 # {val} ({address}). ',
    isCheckingBalance: '检查余额中...',
    balanceIs: '余额为{val}。 ',
    getBalanceError: '获取余额出错。 ',
    isCheckingGwei: '正在检查Gwei... ',
    gweiValid: 'Gwei未达到限制最大值，继续执行。 ',
    gweiOverMax: 'Gwei已达到限制最大值，程序暂停，5秒后再试',
    claimXENProcessing: '开始提取XEN... ',
    estimatingGasProcessing: '正在估算提取XEN所需Gas费... ',
    estimatingGasError: '估算Gas费出错。 ',
    claimAndShareProcessing: '正在执行claim and share XEN... ',
    claimAndShareError: '执行claim and share XEN 出错. ',
    claimAndShareSend: '已发送claim and share XEN 交易, 正在确认上链状态... ',
    claimAndShareSendError: '确认claim and share XEN 交易上链状态出错。 ',
    claimAndShareFinished: '已完成claim and share XEN. ',
    transferProcessing: '开始转账... ',
    sendTransferProcessing: '正在发送转账交易... ',
    sendTransferError: '发送转账交易出错。',
    sentTransfer: '已发送转账交易，正在确认上链状态... ',
    confirmTransferError: '转账交易上链状态出错。 ',
    confirmTransferFinished: '已完成链上转账确认',
}
