export default {
    claimBot: 'XEN Claim Bot',
    mobileVisitNotice: '請使用桌面瀏覽器訪問此頁',
    header: {
        xenft: 'XENFT',
        monitor: 'XEN監控',
        dashboard: '儀表盤',
        portfolio: '我的資產',
        miner: 'Miner',
        claimbot: 'ClaimBot'
    },
    footer: {
        slogan: '建設加密世界新未來',
        intro: 'CryptoCell Labs是一個專註於區塊鏈行業研究、知識傳播、數據分析的行業平臺，力圖幫助業內人士洞察行業走勢、把握市場先機。',
        copyRights: '© 2022 CryptoCell Labs. All Rights Reserved.'
    },
    datetime: {
        days: '天',
        hours: '小時',
        minutes: '分鐘',
        seconds: '秒'
    },
    importFileForm: {
        title: '導入文件',
        desc: '導入包含錢包地址和私鑰的表格文件 (xls, xlsx, csv)',
        placeholder: '選擇文件',
        notFound: '無表格文件',
        notSupported: '文件類型不支持',
        template: '示例文件',
        notAvailable: '沒有可用的地址和私鑰'
    },
    toClaim: '去提取XEN',
    toClaimDesc: '跳轉至提取XEN頁面前，將自動選擇當前可提取的地址並保存至瀏覽器本地存儲',
    addresses: '地址列表',
    clearAddresses: '清空地址',
    totalImported: '共導入',
    currentClaimable: '當前可提取',
    walletAddress: '錢包地址',
    status: '狀態',
    noMintInfo: '無鑄造信息',
    maturity: '到期時間',
    term: '鎖定天數',
    paramsConfig: '參數配置',
    walletAddressToReceiveXEN: '收取XEN和余額的錢包地址',
    maxGwei: '最大Gwei',
    start: '開始',
    continue: '繼續',
    pause: '暫停',
    ended: '已結束',
    startNewTask: '開始新任務',
    configForm: {
        pleaseInput: '請輸入',
        walletAddressFormatError: '錢包地址格式不正確'
    },
    claimTips: {
        title: '提示',
        p1: '本程序是模擬人工操作的，需要確保電腦處於非待機狀態並且網絡環境穩定，開始提取任務後不要關閉此頁面，也不要打開多個瀏覽器標簽頁進行同一操作。',
        p2: '本程序將按表格順序執行提取XEN過程，每提取完一個錢包地址的XEN，將把余額轉至下一個錢包，進行下一個錢包的提取任務，直至最後一個錢包，最後一個錢包的余額將轉至收取XEN的錢包地址。',
        p3: '開始任務前，請確保第一個錢包地址的余額可滿足整個提取和轉賬過程的花費，為避免過程中提前中止，建議多轉一些，剩余部分會轉回收取XEN的錢包地址。',
        p4: '過程中可調整最大Gwei，收取XEN的錢包地址不可調整。',
        p5: '本程序代碼已開源，可點擊右上角Github圖標查看詳情，使用過程中的網絡通訊僅包含必要的與以太坊節點之間的通訊，產生的內容將保存在瀏覽器本地存儲中。'
    },
    logs: '日誌',
    logsType: {
        noContent: '暫無內容'
    },
    totalAddresses: '地址總數',
    claimStatus: '提取狀態',
    transferStatus: '轉賬狀態',
    balance: '余額',
    actions: '操作',
    taskStarted: '任務開始。',
    taskEnded: '任務結束。',
    taskPaused: '任務暫停。',
    taskContinue: '任務繼續。',
    executingAddressItem: '正在執行 # {val} ({address}). ',
    isCheckingBalance: '檢查余額中...',
    balanceIs: '余額為{val}。 ',
    getBalanceError: '獲取余額出錯。 ',
    isCheckingGwei: '正在檢查Gwei... ',
    gweiValid: 'Gwei未達到限製最大值，繼續執行。 ',
    gweiOverMax: 'Gwei已達到限製最大值，程序暫停，5秒後再試',
    claimXENProcessing: '開始提取XEN... ',
    estimatingGasProcessing: '正在估算提取XEN所需Gas費... ',
    estimatingGasError: '估算Gas費出錯。 ',
    claimAndShareProcessing: '正在執行claim and share XEN... ',
    claimAndShareError: '執行claim and share XEN 出錯. ',
    claimAndShareSend: '已發送claim and share XEN 交易, 正在確認上鏈狀態... ',
    claimAndShareSendError: '確認claim and share XEN 交易上鏈狀態出錯。 ',
    claimAndShareFinished: '已完成claim and share XEN. ',
    transferProcessing: '開始轉賬... ',
    sendTransferProcessing: '正在發送轉賬交易... ',
    sendTransferError: '發送轉賬交易出錯。',
    sentTransfer: '已發送轉賬交易，正在確認上鏈狀態... ',
    confirmTransferError: '轉賬交易上鏈狀態出錯。 ',
    confirmTransferFinished: '已完成鏈上轉賬確認',
}
